INSERT INTO TEAM (id,name) VALUES ('1','Arsenal');
INSERT INTO TEAM (id,name) VALUES ('2','Chelsea');
INSERT INTO TEAM (id,name) VALUES ('3','Manchester Utd.');
INSERT INTO TEAM (id,name) VALUES ('4','Manchester City');
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (1,35,'200102','Alves Soares, Cedric Riciardo',1);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (2,18,'200104','Dos Santos Magalhães, Gabriel',1);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (3,23,'200109','Elneny, Mohamed Naser Elsayed',1);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (4,18,'200110','Fernando De Jesus, Gabriel',1);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (5,35,'200110','Ferreira Vieira, Fabio Daniel',1);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (6,38,'200111','Holding, Robert Samuel',2);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (7,17,'200303','Igaba-Ishimwe, George Lewis',2);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (8,26,'200305','Nelson, Reiss',2);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (9,32,'200307','Nketiah, Edward Keddar',2);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (10,34,'200409','Odegaard, Martin',2);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (11,30,'200603','Partey, Thomas Teye',3);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (12,17,'200605','Ramsdale, Aaron',3);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (13,35,'200702','Sambi Lokonga, Albert-Mboyo',3);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (14,21,'200703','Smith, Matthew Gerrard',3);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (15,24,'200704','Smith Rowe, Emile',3);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (16,33,'200709','Tierney, Kieran',4);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (17,26,'200803','Tomiyasu, Takehiro',4);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (18,37,'200805','Turner, Matthew',4);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (19,37,'200809','White, Benjamin',4);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (20,33,'200902','Xhaka, Granit',4);
INSERT INTO PLAYER (id,age, license_date, name,team_Id) VALUES (21,34,'200903','Zinchenko, Oleksandr',4);